"""Shared, framework-independent ResearchMind data models."""

from researchmind.models.conversation import Conversation
from researchmind.models.code_change import (
    CodeChangeAuditAction,
    CodeChangeAuditEvent,
    CodeChangeAuditStatus,
    CodeChangeProposal,
    CodeChangeReceipt,
    CodeChangeRollbackReceipt,
    CodeFileSnapshot,
)
from researchmind.models.code_context import (
    CodeContext,
    CodeFile,
    CodeFileStatus,
    CodeProject,
    CodeProjectSummary,
    CodeSymbol,
)
from researchmind.models.code_selection import (
    CodeExtractionMethod,
    CodeLanguage,
    CodeSelection,
    CodeSymbolKind,
)
from researchmind.models.document import Document
from researchmind.models.evidence_link import (
    CodeEvidenceReference,
    EvidenceGenerationMethod,
    EvidenceLink,
    EvidenceRelation,
    PaperEvidenceKind,
    PaperEvidenceReference,
)
from researchmind.models.figure_region import FigureRegion
from researchmind.models.formula import (
    FormulaCrop,
    FormulaExecution,
    FormulaRecognitionCandidate,
    FormulaRecognitionStatus,
    FormulaRegion,
    FormulaRegionKind,
    FormulaSourceKind,
    FormulaTransferPreview,
)
from researchmind.models.knowledge_note import KnowledgeNote
from researchmind.models.note_draft import (
    EvidenceKind,
    EvidenceOrigin,
    EvidenceSourceState,
    EvidenceSnapshot,
    NoteDraft,
    NoteDraftPreview,
    NoteDraftStatus,
)
from researchmind.models.library import (
    AssetKind,
    AssetReference,
    LibraryEntry,
    LibraryBackupResult,
    LibraryImportResult,
    LibraryItemKind,
    LibraryRecord,
    LibraryRestoreResult,
    UploadedFileData,
)
from researchmind.models.maintenance import (
    ConfigurationCheck,
    ConfigurationReport,
    DiagnosticStatus,
    MarkdownBackupResult,
    MarkdownRestoreResult,
)
from researchmind.models.message import Message, MessageRole, MessageTask
from researchmind.models.page import Page
from researchmind.models.reading_selection import ReadingSelection
from researchmind.models.read_only_assistant import (
    AssistantAction,
    AssistantActionName,
    AssistantAuditEvent,
    AssistantAuditStatus,
    AssistantStatus,
    AssistantStopReason,
    AssistantToolName,
    AssistantToolResult,
    AssistantToolStatus,
    ReadOnlyAssistantSession,
)
from researchmind.models.research_context import ResearchContext
from researchmind.models.text_block import BoundingBox, TextBlock, TextBlockRole
from researchmind.models.zotero import (
    ZoteroAttachment,
    ZoteroBrowseResult,
    ZoteroConnection,
    ZoteroDownloadedFile,
    ZoteroItem,
    ZoteroItemDetails,
    ZoteroLibraryType,
    ZoteroSourceLink,
)

__all__ = [
    "CodeLanguage",
    "BoundingBox",
    "CodeChangeAuditAction",
    "CodeChangeAuditEvent",
    "CodeChangeAuditStatus",
    "CodeChangeProposal",
    "CodeChangeReceipt",
    "CodeChangeRollbackReceipt",
    "CodeContext",
    "CodeExtractionMethod",
    "CodeFile",
    "CodeFileSnapshot",
    "CodeFileStatus",
    "CodeProject",
    "CodeProjectSummary",
    "CodeSelection",
    "CodeSymbol",
    "CodeSymbolKind",
    "Conversation",
    "Document",
    "CodeEvidenceReference",
    "EvidenceGenerationMethod",
    "EvidenceLink",
    "EvidenceRelation",
    "FigureRegion",
    "FormulaCrop",
    "FormulaExecution",
    "FormulaRecognitionCandidate",
    "FormulaRecognitionStatus",
    "FormulaRegion",
    "FormulaRegionKind",
    "FormulaSourceKind",
    "FormulaTransferPreview",
    "KnowledgeNote",
    "EvidenceKind",
    "EvidenceOrigin",
    "EvidenceSourceState",
    "EvidenceSnapshot",
    "NoteDraft",
    "NoteDraftPreview",
    "NoteDraftStatus",
    "AssetKind",
    "AssetReference",
    "LibraryEntry",
    "LibraryBackupResult",
    "LibraryImportResult",
    "LibraryItemKind",
    "LibraryRecord",
    "LibraryRestoreResult",
    "UploadedFileData",
    "ConfigurationCheck",
    "ConfigurationReport",
    "DiagnosticStatus",
    "MarkdownBackupResult",
    "MarkdownRestoreResult",
    "Message",
    "MessageRole",
    "MessageTask",
    "Page",
    "PaperEvidenceKind",
    "PaperEvidenceReference",
    "ReadingSelection",
    "AssistantAction",
    "AssistantActionName",
    "AssistantAuditEvent",
    "AssistantAuditStatus",
    "AssistantStatus",
    "AssistantStopReason",
    "AssistantToolName",
    "AssistantToolResult",
    "AssistantToolStatus",
    "ReadOnlyAssistantSession",
    "ResearchContext",
    "TextBlock",
    "TextBlockRole",
    "ZoteroAttachment",
    "ZoteroBrowseResult",
    "ZoteroConnection",
    "ZoteroDownloadedFile",
    "ZoteroItem",
    "ZoteroItemDetails",
    "ZoteroLibraryType",
    "ZoteroSourceLink",
]
